// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBudjos4hArypi0UX7LMw1KI_NR3ZuJs7A',
    appId: '1:878597558802:web:17d793ec18c604e4853ecb',
    messagingSenderId: '878597558802',
    projectId: 'hotel-booking-system-17',
    authDomain: 'hotel-booking-system-17.firebaseapp.com',
    storageBucket: 'hotel-booking-system-17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQl27q6ktSibZmicKnFNvvhKQ5r2tDxIQ',
    appId: '1:878597558802:android:5d12d21fd4ee75c7853ecb',
    messagingSenderId: '878597558802',
    projectId: 'hotel-booking-system-17',
    storageBucket: 'hotel-booking-system-17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwX6EBRlsDP__27IXpF-XbDVOsMTPxCE',
    appId: '1:878597558802:ios:d79c8a65299cc333853ecb',
    messagingSenderId: '878597558802',
    projectId: 'hotel-booking-system-17',
    storageBucket: 'hotel-booking-system-17.appspot.com',
    iosBundleId: 'com.example.hotelBookingAdminPanel',
  );
}
